In [9]:
import pandas as pd
import sys
import os
import numpy as np

# add the project root to the Python path to allow for absolute imports
project_root = os.path.abspath(os.path.join(os.getcwd(), '..'))
if project_root not in sys.path:
	sys.path.append(project_root)

In [10]:
data = pd.read_csv(r"/Users/maximilianverwiebe/codingprojects/ml-from-scratch/datasets/car_price_prediction.csv")

data.head()

,Make,Model,Year,Engine Size,Mileage,Fuel Type,Transmission,Price
0,Honda,Model B,2015,3.9,74176,Petrol,Manual,30246.207931
1,Ford,Model C,2014,1.7,94799,Electric,Automatic,22785.747684
2,BMW,Model B,2006,4.1,98385,Electric,Manual,25760.290347
3,Honda,Model B,2015,2.6,88919,Electric,Automatic,25638.003491
4,Honda,Model C,2004,3.4,138482,Petrol,Automatic,21021.386657

In [11]:
from mlfromsc.algorithms.random_forest import RandomForestRegressor
from mlfromsc import TrainTestSplit

In [ ]:
X = data.drop("Price", axis=1)

y = np.log1p(data["Price"])

X = np.array(X)
y = np.array(y)

train_test_split = TrainTestSplit()
X_train, X_test, y_train, y_test = train_test_split.fit(X, y, test_ratio=0.2, seed=42)

In [13]:
rf = RandomForestRegressor(n_trees=100, max_depth=7, min_samples_split=10, max_features=None)
rf.fit(X_train, y_train)

[1 0 2 3 6 5 4]
[5 0 2 1 3 6 4]
[6 1 3 4 0 5 2]
[4 1 2 0 3 5 6]
[6 1 4 2 5 0 3]
[6 1 0 3 5 2 4]
[3 6 0 5 4 1 2]
[2 4 5 3 1 6 0]
[1 4 2 3 5 0 6]
[0 1 6 2 3 4 5]
[3 1 6 2 4 0 5]
[2 6 0 4 5 1 3]
[1 2 0 3 6 5 4]
[3 1 6 5 4 2 0]
[2 3 0 1 5 6 4]
[6 3 1 5 2 4 0]
[4 1 6 5 2 0 3]
[0 2 1 6 3 4 5]
[0 5 2 4 6 3 1]
[3 1 6 4 5 2 0]
[0 4 5 1 6 3 2]
[3 1 5 2 6 4 0]
[0 6 1 4 2 3 5]
[6 0 4 1 5 2 3]
[6 2 5 3 0 1 4]
[6 4 5 0 3 2 1]
[3 0 5 6 1 4 2]
[4 6 0 1 5 2 3]
[2 6 1 0 5 3 4]
[3 4 6 5 0 2 1]
[5 2 3 0 4 1 6]
[6 1 3 4 2 0 5]
[2 3 5 4 6 0 1]
[6 0 3 4 1 2 5]
[5 0 4 1 2 6 3]
[1 2 5 0 6 3 4]
[2 4 5 6 3 1 0]
[6 1 0 4 2 3 5]
[5 0 6 1 3 2 4]
[6 0 5 4 2 3 1]
[6 4 1 0 5 3 2]
[6 1 3 2 5 0 4]
[4 0 3 2 5 6 1]
[0 2 6 1 5 3 4]
[2 5 4 6 3 1 0]
[0 2 1 3 6 4 5]
[1 2 6 3 5 0 4]
[0 2 6 3 4 5 1]
[4 0 2 3 6 5 1]
[1 6 2 0 5 4 3]
[0 2 4 1 3 5 6]
[1 0 2 3 4 5 6]
[1 4 0 3 5 2 6]
[5 3 4 1 0 6 2]
[1 4 2 0 6 3 5]
[2 4 0 3 1 5 6]
[5 0 3 1 4 2 6]
[5 6 2 1 0 4 3]
[1 5 4 6 2 3 0]
[1 2 3 4 6 5 0]
[1 5 6 3 2 4 0]
[0 6 1 2 3 4 5]
[4 2 6 1 0 5 3]
[6 2 1 0 3 5 4]
[2 5 0 1 6 4 3]
[4 0 2 3 1 6 5]
[1 3 4 6 0 5 2]
[6 1 0 4 5 2 3]
[5 0 4 3 6 2 1]
[6 4 2 1 5 0 3]
[4 0 6 3 5 2 1]
[6 4 0 5 1 3 2]
[2 6 3 1 5 4 0]
[1 5 4 3 6 0 2]
[5 1 3 6 0 2 4]
[2 4 0 1 6 5 3]
[1 5 2 3 4 0 6]
[6 0 3 4 5 2 1]
[5 6 4 1 0 2 3]
[6 3 1 5 4 0 2]
[0 6 3 5 2 1 4]
[3 4 0 1 5 2 6]
[6 5 0 4 3 2 1]
[2 6 5 3 1 4 0]
[4 5 1 3 6 0 2]
[5 3 4 6 0 2 1]
[3 2 5 4 6 0 1]
[6 0 1 4 2 5 3]
[3 1 4 5 2 0 6]
[1 2 5 0 4 3 6]
[4 1 0 5 2 3 6]
[6 5 1 4 0 2 3]
[3 5 0 6 1 2 4]
[0 2 6 1 3 4 5]
[4 5 0 1 3 2 6]
[3 2 0 5 1 6 4]
[1 2 4 5 6 0 3]
[3 4 6 2 5 1 0]
[1 6 4 0 2 3 5]
[5 0 4 6 1 3 2]

In [14]:
from mlfromsc.eval import mean_squared_error, mean_absolute_error, r2_score

y_pred_log = rf.predict(X_test)

# inverse transform the predictions (prices) to the original scale
y_pred = np.expm1(y_pred_log)

y_test_orig = np.expm1(y_test)

mse = mean_squared_error(y_test_orig, y_pred)
mae = mean_absolute_error(y_test_orig, y_pred)
r2 = r2_score(y_test_orig, y_pred)

print(f"MSE: {mse:.2f}")
print(f"MAE: {mae:.2f}")
print(f"R^2 Score: {r2:.2f}")

MSE: 4378572.76
MAE: 1693.88
R^2 Score: 0.85